permalink: /:title.html
auto: true
markdown: rdiscount
title: Milestone
accent: 2d88c9
twitter: axialgames
appId : 123456
phone: lumia710whiteblue #lumia800blue
description: Milestone is an app designed to let you easily view your Github repositories and interact with others, wherever you are. Milestone lets you view the Issues in your repository, and add new ones or comment on existing ones.
#valid options
#	emulator
#	focuss (Samsung Focus S)
#	lumia710blackblue (Nokia Lumia 710, Black base with Blue Accents)
#	lumia710blackyellow (Nokia Lumia 710, Black base with Yellow Accents)
#	lumia710whiteblack (Nokia Lumia 710, White base with Black Accents)
#	lumia710whiteblue (Nokia Lumia 710, White base with Blue Accents)
#	lumia710whitepink (Nokia Lumia 710, White base with Pink Accents)
#	lumia800blue (Nokia Lumia 800, Blue Accents)
#	lumia800black (Nokia Lumia 800, Black Accents)
#	lumia800pink (Nokia Lumia 800, Pink Accents)
#	radar (HTC Radar)
#	titan (HTC Titan)